DROP TABLE IF EXISTS kunde;

/*
DROP TABLE IF EXISTS wartungsverlauf;
DROP TABLE IF EXISTS benachrichtigung;
DROP TABLE IF EXISTS fahrzeug;
DROP TABLE IF EXISTS termin;
DROP TABLE IF EXISTS service;
DROP TABLE IF EXISTS kunde;
DROP TABLE IF EXISTS kostenvorschlag;
DROP TABLE IF EXISTS mechaniker;
DROP TABLE IF EXISTS terminvorschlag;
DROP TABLE IF EXISTS verleihauto;
DROP TABLE IF EXISTS verwalter;
 */