DROP TABLE IF EXISTS termin;
DROP TABLE IF EXISTS reparatur;
DROP TABLE IF EXISTS leihvertrag;
DROP TABLE IF EXISTS reparatur_e;
DROP TABLE IF EXISTS terminvrs;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS kostenvrs;
DROP TABLE IF EXISTS tm_me;
DROP TABLE IF EXISTS kunde;
DROP TABLE IF EXISTS mechaniker;
DROP TABLE IF EXISTS verwalter;
DROP TABLE IF EXISTS fahrzeug;
DROP TABLE IF EXISTS leihfahrzeug;
DROP TABLE IF EXISTS reparaturtyp;
DROP INDEX IF EXISTS reparature__idx ON reparatur_e;
DROP INDEX IF EXISTS leihvertrag__idx ON leihvertrag;
DROP INDEX IF EXISTS leihvertrag__idxv1 ON leihvertrag;

DROP SEQUENCE IF EXISTS kunde_id_seq;
DROP SEQUENCE IF EXISTS mechaniker_id_seq;
DROP SEQUENCE IF EXISTS verwalter_id_seq;
DROP SEQUENCE IF EXISTS fahrzeug_id_seq;
DROP SEQUENCE IF EXISTS reapartur_id_seq;
DROP SEQUENCE IF EXISTS  reparaturtyp_id_seq;
DROP SEQUENCE IF EXISTS reparatureintrag_id_seq;
DROP SEQUENCE IF EXISTS feedback_id_seq;
DROP SEQUENCE IF EXISTS kostenvrs_id_seq;
DROP SEQUENCE IF EXISTS leihfahrzeug_id_seq;
DROP SEQUENCE IF EXISTS  leihvertrag_id_seq;
DROP SEQUENCE IF EXISTS  terminvrs_id_seq;
DROP SEQUENCE IF EXISTS termin_id_seq;
